name: "PR Codeowner Autolabel Action"
description: "Add labels to GitHub PRs based on the contents of CODEOWNERS file"
author: "@mdzhang"

branding:
  icon: "heart"
  color: "red"

inputs:
  filepath:
    description: "Relative path to CODEOWNERS in repo"
    required: false
    default: CODEOWNERS

runs:
  using: node20
  main: dist/index.js
